version: '3.4'

services:
  sora-node:
    image: sora2/substrate:1.0.1
    container_name: sora-mainnet
    command: "--name lux8_test --chain main --validator   --base-path /chain    --unsafe-ws-external --unsafe-rpc-external --rpc-methods=Unsafe --rpc-cors all --prometheus-external  --discover-local --telemetry-url  'wss://telemetry.polkadot.io/submit/ 0'" 
    user: "10000:10000"
    dns:
      - 8.8.8.8
      - 9.9.9.9
      - 1.1.1.1
    ports:
       - 127.0.0.7:9933:9933
       - 127.0.0.7:9944:9944
       - 30333:30333/tcp
       - 30333:30333/udp
       - 127.0.0.7::9615:9615
    volumes:
      - ./chain/:/chain/
    restart: unless-stopped
