global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9100']  
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "substrate_node"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9615"]
